name: scm_ontology
version: "1.0.0"
config-version: 2
profile: scm_ontology

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target"]

vars:
  insurance_rate: 0.004
  handling_usd_per_unit: 0.12

models:
  scm_ontology:
    staging:
      +materialized: view
      +schema: staging
    conformed:
      +materialized: table
      +schema: conformed
