-- Generated from ontology/*.yaml by compile.py; edit the registry, not this file.
-- Sensitivity tags on the conformed columns; both editions. Reapplied after every dbt build,
-- which replaces the tables. Runs as SCM_DEPLOY, which owns the tables and holds APPLY on the
-- tag; it switches no role, so the nightly task can execute it from the code stage.

ALTER TABLE SCM_DEV.CONFORMED.DIM_CUSTOMER MODIFY COLUMN CONTACT_EMAIL SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.DIM_CUSTOMER MODIFY COLUMN CONTACT_NAME SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN BANK_ACCOUNT SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'RESTRICTED';
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN CONTACT_EMAIL SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN CONTACT_NAME SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.FCT_PO_LINE MODIFY COLUMN UNIT_COST SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'RESTRICTED';
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT MODIFY COLUMN FREIGHT_CHARGE SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'RESTRICTED';
