-- Generated from ontology/*.yaml by compile.py; edit the registry, not this file.
-- Enterprise edition: the same registry as row access and tag-based masking on CONFORMED.
-- @enterprise
USE ROLE SCM_ADMIN;

CREATE OR REPLACE ROW ACCESS POLICY SCM_DEV.GOV.PLANT_ACCESS AS (plant STRING) RETURNS BOOLEAN ->
    EXISTS (SELECT 1 FROM SCM_DEV.GOV.ENTITLEMENTS e LEFT JOIN SCM_DEV.CONFORMED.DIM_PLANT p ON p.plant_id = plant
            WHERE IS_ROLE_IN_SESSION(e.role_name) AND (e.scope_kind = 'all'
              OR (e.scope_kind = 'plant' AND e.scope_value = plant)
              OR (e.scope_kind = 'region' AND e.scope_value = p.region)));

CREATE OR REPLACE MASKING POLICY SCM_DEV.GOV.MASK_DIM_CUSTOMER_CONTACT_EMAIL AS (val STRING) RETURNS STRING ->
    CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN val ELSE '***' END;
ALTER TABLE SCM_DEV.CONFORMED.DIM_CUSTOMER MODIFY COLUMN CONTACT_EMAIL UNSET MASKING POLICY;
ALTER TABLE SCM_DEV.CONFORMED.DIM_CUSTOMER MODIFY COLUMN CONTACT_EMAIL SET MASKING POLICY SCM_DEV.GOV.MASK_DIM_CUSTOMER_CONTACT_EMAIL;

CREATE OR REPLACE MASKING POLICY SCM_DEV.GOV.MASK_DIM_CUSTOMER_CONTACT_NAME AS (val STRING) RETURNS STRING ->
    CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN val ELSE '***' END;
ALTER TABLE SCM_DEV.CONFORMED.DIM_CUSTOMER MODIFY COLUMN CONTACT_NAME UNSET MASKING POLICY;
ALTER TABLE SCM_DEV.CONFORMED.DIM_CUSTOMER MODIFY COLUMN CONTACT_NAME SET MASKING POLICY SCM_DEV.GOV.MASK_DIM_CUSTOMER_CONTACT_NAME;

CREATE OR REPLACE MASKING POLICY SCM_DEV.GOV.MASK_DIM_SUPPLIER_BANK_ACCOUNT AS (val STRING) RETURNS STRING ->
    CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('PROCUREMENT_ROLE') THEN val ELSE '***' END;
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN BANK_ACCOUNT UNSET MASKING POLICY;
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN BANK_ACCOUNT SET MASKING POLICY SCM_DEV.GOV.MASK_DIM_SUPPLIER_BANK_ACCOUNT;

CREATE OR REPLACE MASKING POLICY SCM_DEV.GOV.MASK_DIM_SUPPLIER_CONTACT_EMAIL AS (val STRING) RETURNS STRING ->
    CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN val ELSE '***' END;
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN CONTACT_EMAIL UNSET MASKING POLICY;
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN CONTACT_EMAIL SET MASKING POLICY SCM_DEV.GOV.MASK_DIM_SUPPLIER_CONTACT_EMAIL;

CREATE OR REPLACE MASKING POLICY SCM_DEV.GOV.MASK_DIM_SUPPLIER_CONTACT_NAME AS (val STRING) RETURNS STRING ->
    CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN val ELSE '***' END;
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN CONTACT_NAME UNSET MASKING POLICY;
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN CONTACT_NAME SET MASKING POLICY SCM_DEV.GOV.MASK_DIM_SUPPLIER_CONTACT_NAME;

CREATE OR REPLACE MASKING POLICY SCM_DEV.GOV.MASK_FCT_PO_LINE_UNIT_COST AS (val FLOAT) RETURNS FLOAT ->
    CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('PROCUREMENT_ROLE') THEN val ELSE NULL END;
ALTER TABLE SCM_DEV.CONFORMED.FCT_PO_LINE MODIFY COLUMN UNIT_COST UNSET MASKING POLICY;
ALTER TABLE SCM_DEV.CONFORMED.FCT_PO_LINE MODIFY COLUMN UNIT_COST SET MASKING POLICY SCM_DEV.GOV.MASK_FCT_PO_LINE_UNIT_COST;

CREATE OR REPLACE MASKING POLICY SCM_DEV.GOV.MASK_FCT_SHIPMENT_FREIGHT_CHARGE AS (val FLOAT) RETURNS FLOAT ->
    CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('PROCUREMENT_ROLE') THEN val ELSE NULL END;
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT MODIFY COLUMN FREIGHT_CHARGE UNSET MASKING POLICY;
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT MODIFY COLUMN FREIGHT_CHARGE SET MASKING POLICY SCM_DEV.GOV.MASK_FCT_SHIPMENT_FREIGHT_CHARGE;

ALTER TABLE SCM_DEV.CONFORMED.FCT_SALES_ORDER_LINE DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_SALES_ORDER_LINE ADD ROW ACCESS POLICY SCM_DEV.GOV.PLANT_ACCESS ON (plant_id);
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT ADD ROW ACCESS POLICY SCM_DEV.GOV.PLANT_ACCESS ON (plant_id);
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT_LINE DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT_LINE ADD ROW ACCESS POLICY SCM_DEV.GOV.PLANT_ACCESS ON (plant_id);
ALTER TABLE SCM_DEV.CONFORMED.FCT_PO_LINE DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_PO_LINE ADD ROW ACCESS POLICY SCM_DEV.GOV.PLANT_ACCESS ON (plant_id);
ALTER TABLE SCM_DEV.CONFORMED.FCT_INVENTORY_MONTH DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_INVENTORY_MONTH ADD ROW ACCESS POLICY SCM_DEV.GOV.PLANT_ACCESS ON (plant_id);
-- @end
