-- Resume the operational loop, children before the root.
USE ROLE SCM_DEPLOY;
ALTER TASK {{DB}}.OPS.LOOP_RECORD RESUME;
ALTER TASK {{DB}}.OPS.LOOP_IDENTITY RESUME;
ALTER TASK {{DB}}.OPS.LOOP_GLOSSARY RESUME;
ALTER TASK {{DB}}.OPS.LOOP_TAGS RESUME;
ALTER TASK {{DB}}.OPS.LOOP_DBT RESUME;
ALTER TASK {{DB}}.OPS.LOOP_ROOT RESUME;
ALTER TASK {{DB}}.OPS.WEEKLY_COST_REPORT RESUME;
