-- Account-level settings for the SCM Ontology project.
-- Run once by ACCOUNTADMIN before environment setup.

USE ROLE ACCOUNTADMIN;

-- Session defaults
ALTER ACCOUNT SET TIMEZONE = 'UTC';
ALTER ACCOUNT SET TIMESTAMP_INPUT_FORMAT = 'AUTO';
ALTER ACCOUNT SET TIMESTAMP_OUTPUT_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS.FF3TZH:TZM';

