-- Functional role hierarchy for the SCM Ontology project.
-- SCM_ADMIN > SCM_DEPLOY > persona roles > SCM_READER.

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS SCM_ADMIN
    COMMENT = 'Full administrative access to the SCM Ontology project';
CREATE ROLE IF NOT EXISTS SCM_DEPLOY
    COMMENT = 'Deployment role for CI/CD pipelines';
CREATE ROLE IF NOT EXISTS PLANNING_ROLE
    COMMENT = 'Supply chain planning persona';
CREATE ROLE IF NOT EXISTS PROCUREMENT_ROLE
    COMMENT = 'Procurement and sourcing persona';
CREATE ROLE IF NOT EXISTS LOGISTICS_ROLE
    COMMENT = 'Logistics and transportation persona';
CREATE ROLE IF NOT EXISTS EXECUTIVE_ROLE
    COMMENT = 'Executive and finance persona';
CREATE ROLE IF NOT EXISTS SCM_READER
    COMMENT = 'Read-only base role for all SCM users';

-- Hierarchy
GRANT ROLE SCM_DEPLOY TO ROLE SCM_ADMIN;
GRANT ROLE PLANNING_ROLE TO ROLE SCM_DEPLOY;
GRANT ROLE PROCUREMENT_ROLE TO ROLE SCM_DEPLOY;
GRANT ROLE LOGISTICS_ROLE TO ROLE SCM_DEPLOY;
GRANT ROLE EXECUTIVE_ROLE TO ROLE SCM_DEPLOY;
GRANT ROLE SCM_READER TO ROLE PLANNING_ROLE;
GRANT ROLE SCM_READER TO ROLE PROCUREMENT_ROLE;
GRANT ROLE SCM_READER TO ROLE LOGISTICS_ROLE;
GRANT ROLE SCM_READER TO ROLE EXECUTIVE_ROLE;

-- Grant SCM_ADMIN to SYSADMIN so it is reachable from the standard hierarchy
GRANT ROLE SCM_ADMIN TO ROLE SYSADMIN;

-- Service user for the SPCS container (key-pair auth, no password)
CREATE USER IF NOT EXISTS SCM_SERVICE_USER
    DEFAULT_ROLE = SCM_READER
    COMMENT = 'Service account for the STRATA SPCS container'
    MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE SCM_READER TO USER SCM_SERVICE_USER;
