-- Databases and schemas for each environment.
-- Run three times with substitution or use a parameterised script.
-- This file shows the template for one environment; replace {{DB}} with
-- SCM_DEV, SCM_TEST or SCM_PROD.

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS {{DB}}
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'SCM Ontology {{ENV}} environment';

CREATE SCHEMA IF NOT EXISTS {{DB}}.RAW
    COMMENT = 'Raw ingested data from source systems';
CREATE SCHEMA IF NOT EXISTS {{DB}}.STAGING
    COMMENT = 'Staging models — cleaned and typed';
CREATE SCHEMA IF NOT EXISTS {{DB}}.CONFORMED
    COMMENT = 'Conformed dimensions and facts'
    DATA_RETENTION_TIME_IN_DAYS = 90;
CREATE SCHEMA IF NOT EXISTS {{DB}}.SEMANTIC
    COMMENT = 'Semantic views, glossary and governed layer';
CREATE SCHEMA IF NOT EXISTS {{DB}}.AGENT
    COMMENT = 'Cortex Agent and governed procedures';
CREATE SCHEMA IF NOT EXISTS {{DB}}.AUDIT
    COMMENT = 'Answer audit log and evaluation results'
    DATA_RETENTION_TIME_IN_DAYS = 90;
CREATE SCHEMA IF NOT EXISTS {{DB}}.EVAL
    COMMENT = 'Evaluation truth data and test artefacts';
CREATE SCHEMA IF NOT EXISTS {{DB}}.OPS
    COMMENT = 'Operational metadata — freshness, dbt runs, alerts';

-- Warehouses
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS SCM_WH_DEV
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Development warehouse';

CREATE WAREHOUSE IF NOT EXISTS SCM_WH_TEST
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Test/CI warehouse';

CREATE WAREHOUSE IF NOT EXISTS SCM_WH_PROD
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Production warehouse';

-- Grants: each persona role gets USAGE on the prod warehouse
USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE {{DB}} TO ROLE SCM_DEPLOY;
GRANT USAGE ON DATABASE {{DB}} TO ROLE SCM_READER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{DB}} TO ROLE SCM_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DB}}.CONFORMED TO ROLE SCM_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA {{DB}}.CONFORMED TO ROLE SCM_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DB}}.SEMANTIC TO ROLE SCM_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA {{DB}}.SEMANTIC TO ROLE SCM_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DB}}.AUDIT TO ROLE SCM_READER;

-- SCM_DEPLOY gets full DDL on all schemas
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE {{DB}} TO ROLE SCM_DEPLOY;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE {{DB}} TO ROLE SCM_DEPLOY;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE {{DB}} TO ROLE SCM_DEPLOY;
