-- Resource monitors with notify and suspend thresholds.

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR SCM_DEV_MONITOR
    WITH
        CREDIT_QUOTA = 50
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
        TRIGGERS
            ON 75 PERCENT DO NOTIFY
            ON 90 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE OR REPLACE RESOURCE MONITOR SCM_TEST_MONITOR
    WITH
        CREDIT_QUOTA = 100
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
        TRIGGERS
            ON 75 PERCENT DO NOTIFY
            ON 90 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE OR REPLACE RESOURCE MONITOR SCM_PROD_MONITOR
    WITH
        CREDIT_QUOTA = 200
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
        TRIGGERS
            ON 50 PERCENT DO NOTIFY
            ON 75 PERCENT DO NOTIFY
            ON 90 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- Assign monitors to warehouses
ALTER WAREHOUSE SCM_WH_DEV SET RESOURCE_MONITOR = SCM_DEV_MONITOR;
ALTER WAREHOUSE SCM_WH_TEST SET RESOURCE_MONITOR = SCM_TEST_MONITOR;
ALTER WAREHOUSE SCM_WH_PROD SET RESOURCE_MONITOR = SCM_PROD_MONITOR;
