-- The environment's resource monitor, then its warehouse created under it, so no credit is
-- spent on a warehouse that is not capped.

USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS SCM_{{ENV}}_MONITOR
    WITH
        CREDIT_QUOTA = {{MONITOR_QUOTA}}
        FREQUENCY = MONTHLY
        START_TIMESTAMP = IMMEDIATELY
        TRIGGERS
            ON 75 PERCENT DO NOTIFY
            ON 90 PERCENT DO SUSPEND
            ON 100 PERCENT DO SUSPEND_IMMEDIATE;

CREATE WAREHOUSE IF NOT EXISTS {{WH}}
    WAREHOUSE_SIZE = '{{WH_SIZE}}'
    AUTO_SUSPEND = {{AUTO_SUSPEND}}
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    RESOURCE_MONITOR = SCM_{{ENV}}_MONITOR
    COMMENT = 'STRATA {{ENV}} warehouse';

GRANT USAGE, OPERATE ON WAREHOUSE {{WH}} TO ROLE SCM_DEPLOY;
GRANT USAGE ON WAREHOUSE {{WH}} TO ROLE SCM_READER;
