-- Generated from ontology/*.yaml by compile.py; edit the registry, not this file.
-- Standard edition: controls realised as compiled secure views. Rows are scoped by
-- GOV.ENTITLEMENTS through IS_ROLE_IN_SESSION; governed columns follow entitlements.yaml.
USE ROLE SCM_DEPLOY;

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.DIM_CARRIER
  COMMENT = 'Governed read of CONFORMED.DIM_CARRIER'
AS
SELECT t.*
FROM SCM_DEV.CONFORMED.DIM_CARRIER t;

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.DIM_CUSTOMER
  COMMENT = 'Governed read of CONFORMED.DIM_CUSTOMER'
AS
SELECT t.* EXCLUDE (CONTACT_EMAIL, CONTACT_NAME), CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN t.CONTACT_EMAIL ELSE '***' END AS CONTACT_EMAIL, CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN t.CONTACT_NAME ELSE '***' END AS CONTACT_NAME
FROM SCM_DEV.CONFORMED.DIM_CUSTOMER t;

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.DIM_PART
  COMMENT = 'Governed read of CONFORMED.DIM_PART'
AS
SELECT t.*
FROM SCM_DEV.CONFORMED.DIM_PART t;

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.DIM_PLANT
  COMMENT = 'Governed read of CONFORMED.DIM_PLANT'
AS
SELECT t.*
FROM SCM_DEV.CONFORMED.DIM_PLANT t
WHERE EXISTS (SELECT 1 FROM SCM_DEV.GOV.ENTITLEMENTS e WHERE IS_ROLE_IN_SESSION(e.role_name) AND (e.scope_kind = 'all' OR (e.scope_kind = 'plant' AND e.scope_value = t.plant_id) OR (e.scope_kind = 'region' AND e.scope_value = t.region)));

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.DIM_SUPPLIER
  COMMENT = 'Governed read of CONFORMED.DIM_SUPPLIER'
AS
SELECT t.* EXCLUDE (BANK_ACCOUNT, CONTACT_EMAIL, CONTACT_NAME), CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('PROCUREMENT_ROLE') THEN t.BANK_ACCOUNT ELSE '***' END AS BANK_ACCOUNT, CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN t.CONTACT_EMAIL ELSE '***' END AS CONTACT_EMAIL, CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN t.CONTACT_NAME ELSE '***' END AS CONTACT_NAME
FROM SCM_DEV.CONFORMED.DIM_SUPPLIER t;

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.FCT_INVENTORY_MONTH
  COMMENT = 'Governed read of CONFORMED.FCT_INVENTORY_MONTH'
AS
SELECT t.*
FROM SCM_DEV.CONFORMED.FCT_INVENTORY_MONTH t
LEFT JOIN SCM_DEV.CONFORMED.DIM_PLANT sp ON sp.plant_id = t.plant_id
WHERE EXISTS (SELECT 1 FROM SCM_DEV.GOV.ENTITLEMENTS e WHERE IS_ROLE_IN_SESSION(e.role_name) AND (e.scope_kind = 'all' OR (e.scope_kind = 'plant' AND e.scope_value = t.plant_id) OR (e.scope_kind = 'region' AND e.scope_value = sp.region)));

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.FCT_PO_LINE
  COMMENT = 'Governed read of CONFORMED.FCT_PO_LINE'
AS
SELECT t.* EXCLUDE (UNIT_COST), CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('PROCUREMENT_ROLE') THEN t.UNIT_COST ELSE NULL END AS UNIT_COST
FROM SCM_DEV.CONFORMED.FCT_PO_LINE t
LEFT JOIN SCM_DEV.CONFORMED.DIM_PLANT sp ON sp.plant_id = t.plant_id
WHERE EXISTS (SELECT 1 FROM SCM_DEV.GOV.ENTITLEMENTS e WHERE IS_ROLE_IN_SESSION(e.role_name) AND (e.scope_kind = 'all' OR (e.scope_kind = 'plant' AND e.scope_value = t.plant_id) OR (e.scope_kind = 'region' AND e.scope_value = sp.region)));

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.FCT_SALES_ORDER_LINE
  COMMENT = 'Governed read of CONFORMED.FCT_SALES_ORDER_LINE'
AS
SELECT t.*
FROM SCM_DEV.CONFORMED.FCT_SALES_ORDER_LINE t
LEFT JOIN SCM_DEV.CONFORMED.DIM_PLANT sp ON sp.plant_id = t.plant_id
WHERE EXISTS (SELECT 1 FROM SCM_DEV.GOV.ENTITLEMENTS e WHERE IS_ROLE_IN_SESSION(e.role_name) AND (e.scope_kind = 'all' OR (e.scope_kind = 'plant' AND e.scope_value = t.plant_id) OR (e.scope_kind = 'region' AND e.scope_value = sp.region)));

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.FCT_SHIPMENT
  COMMENT = 'Governed read of CONFORMED.FCT_SHIPMENT'
AS
SELECT t.* EXCLUDE (FREIGHT_CHARGE), CASE WHEN IS_ROLE_IN_SESSION('SCM_ADMIN') OR IS_ROLE_IN_SESSION('PROCUREMENT_ROLE') THEN t.FREIGHT_CHARGE ELSE NULL END AS FREIGHT_CHARGE
FROM SCM_DEV.CONFORMED.FCT_SHIPMENT t
LEFT JOIN SCM_DEV.CONFORMED.DIM_PLANT sp ON sp.plant_id = t.plant_id
WHERE EXISTS (SELECT 1 FROM SCM_DEV.GOV.ENTITLEMENTS e WHERE IS_ROLE_IN_SESSION(e.role_name) AND (e.scope_kind = 'all' OR (e.scope_kind = 'plant' AND e.scope_value = t.plant_id) OR (e.scope_kind = 'region' AND e.scope_value = sp.region)));

CREATE OR REPLACE SECURE VIEW SCM_DEV.SEMANTIC_BASE.FCT_SHIPMENT_LINE
  COMMENT = 'Governed read of CONFORMED.FCT_SHIPMENT_LINE'
AS
SELECT t.*
FROM SCM_DEV.CONFORMED.FCT_SHIPMENT_LINE t
LEFT JOIN SCM_DEV.CONFORMED.DIM_PLANT sp ON sp.plant_id = t.plant_id
WHERE EXISTS (SELECT 1 FROM SCM_DEV.GOV.ENTITLEMENTS e WHERE IS_ROLE_IN_SESSION(e.role_name) AND (e.scope_kind = 'all' OR (e.scope_kind = 'plant' AND e.scope_value = t.plant_id) OR (e.scope_kind = 'region' AND e.scope_value = sp.region)));
