-- Deploy the STRATA service on SPCS.

USE ROLE SCM_DEPLOY;
USE DATABASE {{DB}};

-- Create image repository if not exists
CREATE IMAGE REPOSITORY IF NOT EXISTS {{DB}}.AGENT.IMAGE_REPO;

-- Create the service
CREATE SERVICE IF NOT EXISTS {{DB}}.AGENT.STRATA_SERVICE
    IN COMPUTE POOL SCM_POOL_{{ENV}}
    FROM SPECIFICATION_FILE = 'snowflake/spcs/service_spec.yaml'
    COMMENT = 'STRATA governed supply chain ontology service';

-- Grant access to the public endpoint
GRANT SERVICE ROLE {{DB}}.AGENT.STRATA_SERVICE!ALL_ENDPOINTS_USAGE TO ROLE PLANNING_ROLE;
GRANT SERVICE ROLE {{DB}}.AGENT.STRATA_SERVICE!ALL_ENDPOINTS_USAGE TO ROLE PROCUREMENT_ROLE;
GRANT SERVICE ROLE {{DB}}.AGENT.STRATA_SERVICE!ALL_ENDPOINTS_USAGE TO ROLE LOGISTICS_ROLE;
GRANT SERVICE ROLE {{DB}}.AGENT.STRATA_SERVICE!ALL_ENDPOINTS_USAGE TO ROLE EXECUTIVE_ROLE;
