-- Generated from ontology/*.yaml by compile.py; edit the registry, not this file.
-- Run from the repository stage after GIT FETCH; each view is created beside the previous version.
USE DATABASE SCM_DEV;
USE SCHEMA SEMANTIC;

CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC',
  (SELECT LISTAGG($1, '\n') FROM @SEMANTIC.VIEW_YAML/scm_governed_v1.yaml (FILE_FORMAT => 'SEMANTIC.YAML_LINES')));

CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC',
  (SELECT LISTAGG($1, '\n') FROM @SEMANTIC.VIEW_YAML/planning_sv_v1.yaml (FILE_FORMAT => 'SEMANTIC.YAML_LINES')));

CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC',
  (SELECT LISTAGG($1, '\n') FROM @SEMANTIC.VIEW_YAML/procurement_sv_v1.yaml (FILE_FORMAT => 'SEMANTIC.YAML_LINES')));

CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC',
  (SELECT LISTAGG($1, '\n') FROM @SEMANTIC.VIEW_YAML/logistics_sv_v1.yaml (FILE_FORMAT => 'SEMANTIC.YAML_LINES')));

CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC',
  (SELECT LISTAGG($1, '\n') FROM @SEMANTIC.VIEW_YAML/executive_sv_v1.yaml (FILE_FORMAT => 'SEMANTIC.YAML_LINES')));
