# Generated from ontology/*.yaml by compile.py; edit the registry, not this file.

USE DATABASE SCM_DEV;
USE SCHEMA SEMANTIC;

-- Deploy SCM_GOVERNED_V1
SELECT SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC.SCM_GOVERNED_V1', $$@SEMANTIC.VIEW_YAML/scm_governed_v1.yaml$$);

-- Deploy PLANNING_SV_V1
SELECT SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC.PLANNING_SV_V1', $$@SEMANTIC.VIEW_YAML/planning_sv_v1.yaml$$);

-- Deploy PROCUREMENT_SV_V1
SELECT SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC.PROCUREMENT_SV_V1', $$@SEMANTIC.VIEW_YAML/procurement_sv_v1.yaml$$);

-- Deploy LOGISTICS_SV_V1
SELECT SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC.LOGISTICS_SV_V1', $$@SEMANTIC.VIEW_YAML/logistics_sv_v1.yaml$$);

-- Deploy EXECUTIVE_SV_V1
SELECT SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SEMANTIC.EXECUTIVE_SV_V1', $$@SEMANTIC.VIEW_YAML/executive_sv_v1.yaml$$);
