-- Generated from ontology/*.yaml by compile.py; edit the registry, not this file.
-- Validates every view in a scratch schema; nothing is left behind.
CREATE OR REPLACE TRANSIENT SCHEMA SCM_DEV.SCRATCH_SV;
CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SCRATCH_SV',
  (SELECT LISTAGG($1, '\n') FROM @SCM_DEV.SEMANTIC.VIEW_YAML/scm_governed_v1.yaml (FILE_FORMAT => 'SCM_DEV.SEMANTIC.YAML_LINES')), TRUE);
CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SCRATCH_SV',
  (SELECT LISTAGG($1, '\n') FROM @SCM_DEV.SEMANTIC.VIEW_YAML/planning_sv_v1.yaml (FILE_FORMAT => 'SCM_DEV.SEMANTIC.YAML_LINES')), TRUE);
CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SCRATCH_SV',
  (SELECT LISTAGG($1, '\n') FROM @SCM_DEV.SEMANTIC.VIEW_YAML/procurement_sv_v1.yaml (FILE_FORMAT => 'SCM_DEV.SEMANTIC.YAML_LINES')), TRUE);
CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SCRATCH_SV',
  (SELECT LISTAGG($1, '\n') FROM @SCM_DEV.SEMANTIC.VIEW_YAML/logistics_sv_v1.yaml (FILE_FORMAT => 'SCM_DEV.SEMANTIC.YAML_LINES')), TRUE);
CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML('SCM_DEV.SCRATCH_SV',
  (SELECT LISTAGG($1, '\n') FROM @SCM_DEV.SEMANTIC.VIEW_YAML/executive_sv_v1.yaml (FILE_FORMAT => 'SCM_DEV.SEMANTIC.YAML_LINES')), TRUE);
DROP SCHEMA SCM_DEV.SCRATCH_SV;
