# Generated from ontology/*.yaml by compile.py; edit the registry, not this file.

USE ROLE SCM_ADMIN;
USE DATABASE SCM_DEV;

ALTER TAG SCM_DEV.CONFORMED.SENSITIVITY SET ON COLUMN SCM_DEV.CONFORMED.SUPPLIER.contact_name = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.SUPPLIER MODIFY COLUMN contact_name SET MASKING POLICY SCM_DEV.CONFORMED.MASK_CONFIDENTIAL_STRING;

ALTER TAG SCM_DEV.CONFORMED.SENSITIVITY SET ON COLUMN SCM_DEV.CONFORMED.SUPPLIER.contact_email = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.SUPPLIER MODIFY COLUMN contact_email SET MASKING POLICY SCM_DEV.CONFORMED.MASK_CONFIDENTIAL_STRING;

ALTER TAG SCM_DEV.CONFORMED.SENSITIVITY SET ON COLUMN SCM_DEV.CONFORMED.SUPPLIER.bank_account = 'RESTRICTED';
ALTER TABLE SCM_DEV.CONFORMED.SUPPLIER MODIFY COLUMN bank_account SET MASKING POLICY SCM_DEV.CONFORMED.MASK_RESTRICTED_NUMBER;

ALTER TAG SCM_DEV.CONFORMED.SENSITIVITY SET ON COLUMN SCM_DEV.CONFORMED.SUPPLIERPARTAGREEMENT.unit_cost = 'RESTRICTED';
ALTER TABLE SCM_DEV.CONFORMED.SUPPLIERPARTAGREEMENT MODIFY COLUMN unit_cost SET MASKING POLICY SCM_DEV.CONFORMED.MASK_RESTRICTED_NUMBER;

ALTER TAG SCM_DEV.CONFORMED.SENSITIVITY SET ON COLUMN SCM_DEV.CONFORMED.CUSTOMER.contact_name = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.CUSTOMER MODIFY COLUMN contact_name SET MASKING POLICY SCM_DEV.CONFORMED.MASK_CONFIDENTIAL_STRING;

ALTER TAG SCM_DEV.CONFORMED.SENSITIVITY SET ON COLUMN SCM_DEV.CONFORMED.CUSTOMER.contact_email = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.CUSTOMER MODIFY COLUMN contact_email SET MASKING POLICY SCM_DEV.CONFORMED.MASK_CONFIDENTIAL_STRING;

ALTER TAG SCM_DEV.CONFORMED.SENSITIVITY SET ON COLUMN SCM_DEV.CONFORMED.PURCHASEORDERLINE.unit_cost = 'RESTRICTED';
ALTER TABLE SCM_DEV.CONFORMED.PURCHASEORDERLINE MODIFY COLUMN unit_cost SET MASKING POLICY SCM_DEV.CONFORMED.MASK_RESTRICTED_NUMBER;

ALTER TAG SCM_DEV.CONFORMED.SENSITIVITY SET ON COLUMN SCM_DEV.CONFORMED.GOODSRECEIPT.inspector_name = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.GOODSRECEIPT MODIFY COLUMN inspector_name SET MASKING POLICY SCM_DEV.CONFORMED.MASK_CONFIDENTIAL_STRING;

ALTER TAG SCM_DEV.CONFORMED.SENSITIVITY SET ON COLUMN SCM_DEV.CONFORMED.SHIPMENT.freight_charge = 'RESTRICTED';
ALTER TABLE SCM_DEV.CONFORMED.SHIPMENT MODIFY COLUMN freight_charge SET MASKING POLICY SCM_DEV.CONFORMED.MASK_RESTRICTED_NUMBER;
