-- Generated from ontology/*.yaml by compile.py; edit the registry, not this file.
-- Masking is tag-based: 04_policies.sql attaches one string and one number policy to the
-- SENSITIVITY tag, and each policy reads the tag value. Tagging a column is the whole binding.
USE ROLE SCM_ADMIN;

ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN contact_name SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN contact_email SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.DIM_SUPPLIER MODIFY COLUMN bank_account SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'RESTRICTED';
ALTER TABLE SCM_DEV.CONFORMED.DIM_CUSTOMER MODIFY COLUMN contact_name SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.DIM_CUSTOMER MODIFY COLUMN contact_email SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SCM_DEV.CONFORMED.FCT_PO_LINE MODIFY COLUMN unit_cost SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'RESTRICTED';
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT MODIFY COLUMN freight_charge SET TAG SCM_DEV.CONFORMED.SENSITIVITY = 'RESTRICTED';

-- Persona roles see the plants USER_PLANT_SCOPE grants them; admin and executive see all.
ALTER TABLE SCM_DEV.CONFORMED.FCT_SALES_ORDER_LINE DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_SALES_ORDER_LINE ADD ROW ACCESS POLICY SCM_DEV.CONFORMED.PLANT_ACCESS ON (plant_id);
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT ADD ROW ACCESS POLICY SCM_DEV.CONFORMED.PLANT_ACCESS ON (plant_id);
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT_LINE DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_SHIPMENT_LINE ADD ROW ACCESS POLICY SCM_DEV.CONFORMED.PLANT_ACCESS ON (plant_id);
ALTER TABLE SCM_DEV.CONFORMED.FCT_PO_LINE DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_PO_LINE ADD ROW ACCESS POLICY SCM_DEV.CONFORMED.PLANT_ACCESS ON (plant_id);
ALTER TABLE SCM_DEV.CONFORMED.FCT_INVENTORY_MONTH DROP ALL ROW ACCESS POLICIES;
ALTER TABLE SCM_DEV.CONFORMED.FCT_INVENTORY_MONTH ADD ROW ACCESS POLICY SCM_DEV.CONFORMED.PLANT_ACCESS ON (plant_id);
