-- Generated from ontology/*.yaml by compile.py; edit the registry, not this file.
-- Promote V1. Rollback is this file compiled with --version 0.
USE ROLE SCM_ADMIN;

GRANT SELECT ON SEMANTIC VIEW SCM_DEV.SEMANTIC.SCM_GOVERNED_V1 TO ROLE SCM_READER;
GRANT SELECT ON SEMANTIC VIEW SCM_DEV.SEMANTIC.PLANNING_SV_V1 TO ROLE PLANNING_ROLE;
GRANT SELECT ON SEMANTIC VIEW SCM_DEV.SEMANTIC.PROCUREMENT_SV_V1 TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON SEMANTIC VIEW SCM_DEV.SEMANTIC.LOGISTICS_SV_V1 TO ROLE LOGISTICS_ROLE;
GRANT SELECT ON SEMANTIC VIEW SCM_DEV.SEMANTIC.EXECUTIVE_SV_V1 TO ROLE EXECUTIVE_ROLE;

UPDATE SCM_DEV.SEMANTIC.ACTIVE_VERSION SET version = 1, promoted_at = CURRENT_TIMESTAMP();
