# Generated from ontology/*.yaml by compile.py; edit the registry, not this file.

USE ROLE SECURITYADMIN;

GRANT SELECT ON VIEW SCM_DEV.SEMANTIC.SCM_GOVERNED_V1 TO ROLE SCM_READER;

GRANT SELECT ON VIEW SCM_DEV.SEMANTIC.PLANNING_SV_V1 TO ROLE PLANNING_ROLE;

GRANT SELECT ON VIEW SCM_DEV.SEMANTIC.PROCUREMENT_SV_V1 TO ROLE PROCUREMENT_ROLE;

GRANT SELECT ON VIEW SCM_DEV.SEMANTIC.LOGISTICS_SV_V1 TO ROLE LOGISTICS_ROLE;

GRANT SELECT ON VIEW SCM_DEV.SEMANTIC.EXECUTIVE_SV_V1 TO ROLE EXECUTIVE_ROLE;
